### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by lucasctd** [jz222/logowl#27]
I am trying to push logs to it but I am getting an 400 Http error:

`"{"ok":false,"code":400,"message":"EOF"}"`

I've no idea what's wrong.

May you help me?

Thx

**Comment by jz222** [comment]
Hi, what do you mean by "trying to push logs to it"? Can you please show me the request you are sending and to which endpoint?

**Comment by lucasctd** [comment]
@jz222 sure.
So, I am using [Utopia Logger](https://github.com/utopia-php/logger) package to send the logs to Log Owl.
They have a [LogOwl adapter](https://github.com/utopia-php/logger/blob/main/src/Logger/Adapter/LogOwl.php) which makes a request to your service and send the log for the ticket I created at https://logowl.io.

I dunno, I just ran it again to screenshot the request body submitted by the lib to you but it now worked o.o
